export type AdminMenuItem = {
  key: string;
  label: string;
  href: string;
  group: string;
  keywords?: string[];
  icon?: string;
};

export const ADMIN_MENU: AdminMenuItem[] = [
  {
    key: "dashboard",
    label: "Trang chủ",
    href: "/dashboard",
    group: "Tổng quan",
    keywords: ["home", "tong quan", "trang chu", "dashboard"],
    icon: "dot",
  },
  {
    key: "kpi-daily",
    label: "KPI",
    href: "/kpi/daily",
    group: "Tổng quan",
    keywords: ["kpi", "chi so", "bao cao"],
    icon: "dot",
  },
  {
    key: "ai-kpi-coach",
    label: "Trợ lý công việc",
    href: "/ai/kpi-coach",
    group: "Tổng quan",
    keywords: ["tro ly cong viec", "goi y", "khuyen nghi", "hieu suat"],
    icon: "dot",
  },
  {
    key: "kpi-targets",
    label: "Mục tiêu KPI",
    href: "/kpi/targets",
    group: "Tổng quan",
    keywords: ["target", "chi tieu", "kpi target", "ngay trong tuan"],
    icon: "dot",
  },
  {
    key: "goals",
    label: "Mục tiêu ngày/tháng",
    href: "/goals",
    group: "Tổng quan",
    keywords: ["goals", "muc tieu", "doanh thu", "ho so", "chi phi"],
    icon: "dot",
  },
  {
    key: "notifications",
    label: "Thông báo",
    href: "/notifications",
    group: "Tổng quan",
    keywords: ["viec can lam", "task", "nhac viec"],
    icon: "dot",
  },
  {
    key: "leads",
    label: "Khách hàng",
    href: "/leads",
    group: "Khách & Tư vấn",
    keywords: ["lead", "kh", "khach", "khach hang", "data", "sdt", "sđt"],
    icon: "dot",
  },
  {
    key: "leads-board",
    label: "Bảng trạng thái khách hàng",
    href: "/leads/board",
    group: "Khách & Tư vấn",
    keywords: ["pipeline", "kanban", "trang thai", "lead board"],
    icon: "dot",
  },
  {
    key: "outbound",
    label: "Gọi nhắc",
    href: "/outbound",
    group: "Khách & Tư vấn",
    keywords: ["goi nhac", "goi", "sms", "zns", "nhan tin"],
    icon: "dot",
  },
  {
    key: "receipts",
    label: "Phiếu thu",
    href: "/receipts",
    group: "Tài chính",
    keywords: ["thu tien", "bien lai", "receipt", "doanh thu"],
    icon: "dot",
  },
  {
    key: "expenses-monthly",
    label: "Chi phí",
    href: "/expenses/monthly",
    group: "Tài chính",
    keywords: ["chi phi", "expense", "tong hop", "luong co ban"],
    icon: "dot",
  },
  {
    key: "me-payroll",
    label: "Lương của tôi",
    href: "/me/payroll",
    group: "Tài chính",
    keywords: ["payroll", "luong ca nhan", "commission", "hoa hong"],
    icon: "dot",
  },
  {
    key: "hr-payroll",
    label: "Bảng lương",
    href: "/hr/payroll",
    group: "Tài chính",
    keywords: ["payroll", "luong", "hoa hong", "commission"],
    icon: "dot",
  },
  {
    key: "hr-kpi",
    label: "KPI nhân sự",
    href: "/hr/kpi",
    group: "Tài chính",
    keywords: ["kpi nhan su", "hr", "hieu suat"],
    icon: "dot",
  },
  {
    key: "students",
    label: "Học viên",
    href: "/students",
    group: "Học viên & Lịch",
    keywords: ["student", "hoc vien", "hoc vien moi"],
    icon: "dot",
  },
  {
    key: "courses",
    label: "Khóa học",
    href: "/courses",
    group: "Học viên & Lịch",
    keywords: ["course", "khoa", "lop", "dao tao"],
    icon: "dot",
  },
  {
    key: "schedule",
    label: "Lịch học",
    href: "/schedule",
    group: "Học viên & Lịch",
    keywords: ["lich", "ca hoc", "calendar", "lich hoc"],
    icon: "dot",
  },
  {
    key: "admin-student-content",
    label: "Nội dung học viên",
    href: "/admin/student-content",
    group: "Học viên & Lịch",
    keywords: ["noi dung", "tai lieu", "hoc lieu"],
    icon: "dot",
  },
  {
    key: "automation-run",
    label: "Tự động hóa",
    href: "/automation/run",
    group: "Tự động hoá",
    keywords: ["automation", "chay tay", "workflow", "tu dong"],
    icon: "dot",
  },
  {
    key: "automation-logs",
    label: "Nhật ký tự động hóa",
    href: "/automation/logs",
    group: "Tự động hoá",
    keywords: ["log", "lich su chay", "retry", "job"],
    icon: "dot",
  },
  {
    key: "admin-cron",
    label: "Vận hành tự động",
    href: "/admin/cron",
    group: "Tự động hoá",
    keywords: ["cron", "scheduler", "lich chay"],
    icon: "dot",
  },
  {
    key: "admin-scheduler",
    label: "Lập lịch",
    href: "/admin/scheduler",
    group: "Tự động hoá",
    keywords: ["scheduler", "lich", "job"],
    icon: "dot",
  },
  {
    key: "admin-worker",
    label: "Tiến trình gửi tin",
    href: "/admin/worker",
    group: "Tự động hoá",
    keywords: ["worker", "queue", "hang doi", "tin nhan"],
    icon: "dot",
  },
  {
    key: "admin-n8n",
    label: "Luồng n8n",
    href: "/admin/n8n",
    group: "Tự động hoá",
    keywords: ["n8n", "workflow", "integration", "ops"],
    icon: "dot",
  },
  {
    key: "admin-ops",
    label: "Báo cáo",
    href: "/admin/ops",
    group: "Tự động hoá",
    keywords: ["ops pulse", "marketing", "bao cao", "report"],
    icon: "dot",
  },
  {
    key: "marketing",
    label: "Báo cáo marketing",
    href: "/marketing",
    group: "Tự động hoá",
    keywords: ["marketing", "meta", "ads", "bao cao"],
    icon: "dot",
  },
  {
    key: "admin-users",
    label: "Người dùng",
    href: "/admin/users",
    group: "Quản trị",
    keywords: ["user", "tai khoan", "phan quyen"],
    icon: "dot",
  },
  {
    key: "admin-permissions",
    label: "Phân quyền",
    href: "/admin/phan-quyen",
    group: "Quản trị",
    keywords: ["rbac", "phan quyen", "group", "override"],
    icon: "dot",
  },
  {
    key: "admin-guide",
    label: "Hướng dẫn vận hành",
    href: "/admin/guide",
    group: "Quản trị",
    keywords: ["huong dan", "runbook", "quy trinh", "tai lieu"],
    icon: "dot",
  },
  {
    key: "admin-ai-guide",
    label: "Hướng dẫn Trợ lý công việc",
    href: "/admin/huong-dan-ai",
    group: "Quản trị",
    keywords: ["tro ly cong viec", "huong dan ai", "goi y", "kpi"],
    icon: "dot",
  },
  {
    key: "admin-ops-guide",
    label: "Sổ tay vận hành",
    href: "/admin/huong-dan-van-hanh",
    group: "Quản trị",
    keywords: ["so tay", "huong dan van hanh", "quy trinh", "van hanh"],
    icon: "dot",
  },
  {
    key: "api-hub",
    label: "API Hub",
    href: "/api-hub",
    group: "Quản trị",
    keywords: ["api", "integration", "tich hop", "hub", "swagger"],
    icon: "dot",
  },
  {
    key: "admin-branches",
    label: "Chi nhánh",
    href: "/admin/branches",
    group: "Quản trị",
    keywords: ["branch", "co so", "dia diem"],
    icon: "dot",
  },
  {
    key: "admin-assign-leads",
    label: "Phân khách hàng",
    href: "/admin/assign-leads",
    group: "Quản trị",
    keywords: ["phan bo", "chia lead", "chia khach"],
    icon: "dot",
  },
  {
    key: "admin-notifications",
    label: "Quản trị thông báo",
    href: "/admin/notifications",
    group: "Quản trị",
    keywords: ["thong bao", "notification"],
    icon: "dot",
  },
  {
    key: "admin-tuition-plans",
    label: "Gói học phí",
    href: "/admin/tuition-plans",
    group: "Quản trị",
    keywords: ["hoc phi", "tuition", "goi hoc phi"],
    icon: "dot",
  },
  {
    key: "hr-attendance",
    label: "Chấm công",
    href: "/hr/attendance",
    group: "Quản trị",
    keywords: ["attendance", "cong", "diem danh nhan su"],
    icon: "dot",
  },
  {
    key: "hr-salary-profiles",
    label: "Hồ sơ lương",
    href: "/hr/salary-profiles",
    group: "Quản trị",
    keywords: ["salary profile", "muc luong", "ho so"],
    icon: "dot",
  },
];
