export type AdminMenuItem = {
  key: string;
  label: string;
  href: string;
  group: string;
  keywords?: string[];
  icon?: string;
};

/* ── Group-level colour tokens (gradient pair + accent for active state) ── */
export const GROUP_COLORS: Record<string, { from: string; to: string; accent: string; bg: string; text: string; icon: string }> = {
  "Tổng quan": { from: "from-blue-600", to: "to-indigo-600", accent: "bg-blue-600", bg: "bg-blue-50", text: "text-blue-700", icon: "📊" },
  "Khách & Tư vấn": { from: "from-amber-500", to: "to-orange-500", accent: "bg-amber-500", bg: "bg-amber-50", text: "text-amber-700", icon: "👥" },
  "Tài chính": { from: "from-emerald-600", to: "to-teal-600", accent: "bg-emerald-600", bg: "bg-emerald-50", text: "text-emerald-700", icon: "💰" },
  "Học viên & Lịch": { from: "from-violet-600", to: "to-purple-600", accent: "bg-violet-600", bg: "bg-violet-50", text: "text-violet-700", icon: "🎓" },
  "Tự động hoá": { from: "from-rose-500", to: "to-red-500", accent: "bg-rose-500", bg: "bg-rose-50", text: "text-rose-700", icon: "⚡" },
  "Quản trị": { from: "from-slate-700", to: "to-zinc-700", accent: "bg-slate-700", bg: "bg-slate-50", text: "text-slate-700", icon: "⚙️" },
};

export const ADMIN_MENU: AdminMenuItem[] = [
  {
    key: "dashboard",
    label: "Trang chủ",
    href: "/dashboard",
    group: "Tổng quan",
    keywords: ["home", "tong quan", "trang chu", "dashboard"],
    icon: "🏠",
  },
  {
    key: "kpi-daily",
    label: "KPI",
    href: "/kpi/daily",
    group: "Tổng quan",
    keywords: ["kpi", "chi so", "bao cao"],
    icon: "📈",
  },
  {
    key: "ai-kpi-coach",
    label: "Trợ lý công việc",
    href: "/ai/kpi-coach",
    group: "Tổng quan",
    keywords: ["tro ly cong viec", "goi y", "khuyen nghi", "hieu suat"],
    icon: "🤖",
  },
  {
    key: "kpi-targets",
    label: "Mục tiêu KPI",
    href: "/kpi/targets",
    group: "Tổng quan",
    keywords: ["target", "chi tieu", "kpi target", "ngay trong tuan"],
    icon: "🎯",
  },
  {
    key: "goals",
    label: "Mục tiêu ngày/tháng",
    href: "/goals",
    group: "Tổng quan",
    keywords: ["goals", "muc tieu", "doanh thu", "ho so", "chi phi"],
    icon: "📅",
  },
  {
    key: "notifications",
    label: "Thông báo",
    href: "/notifications",
    group: "Tổng quan",
    keywords: ["viec can lam", "task", "nhac viec"],
    icon: "🔔",
  },
  {
    key: "leads",
    label: "Khách hàng",
    href: "/leads",
    group: "Khách & Tư vấn",
    keywords: ["lead", "kh", "khach", "khach hang", "data", "sdt", "sđt"],
    icon: "👤",
  },
  {
    key: "leads-board",
    label: "Bảng trạng thái khách hàng",
    href: "/leads/board",
    group: "Khách & Tư vấn",
    keywords: ["pipeline", "kanban", "trang thai", "lead board"],
    icon: "📋",
  },
  {
    key: "outbound",
    label: "Gọi nhắc",
    href: "/outbound",
    group: "Khách & Tư vấn",
    keywords: ["goi nhac", "goi", "sms", "zns", "nhan tin"],
    icon: "📞",
  },
  {
    key: "receipts",
    label: "Phiếu thu",
    href: "/receipts",
    group: "Tài chính",
    keywords: ["thu tien", "bien lai", "receipt", "doanh thu"],
    icon: "🧾",
  },
  {
    key: "expenses-monthly",
    label: "Chi phí",
    href: "/expenses/monthly",
    group: "Tài chính",
    keywords: ["chi phi", "expense", "tong hop", "luong co ban"],
    icon: "💸",
  },
  {
    key: "me-payroll",
    label: "Lương của tôi",
    href: "/me/payroll",
    group: "Tài chính",
    keywords: ["payroll", "luong ca nhan", "commission", "hoa hong"],
    icon: "💵",
  },
  {
    key: "hr-payroll",
    label: "Bảng lương",
    href: "/hr/payroll",
    group: "Tài chính",
    keywords: ["payroll", "luong", "hoa hong", "commission"],
    icon: "📊",
  },
  {
    key: "hr-kpi",
    label: "KPI nhân sự",
    href: "/hr/kpi",
    group: "Tài chính",
    keywords: ["kpi nhan su", "hr", "hieu suat"],
    icon: "📉",
  },
  {
    key: "students",
    label: "Học viên",
    href: "/students",
    group: "Học viên & Lịch",
    keywords: ["student", "hoc vien", "hoc vien moi"],
    icon: "🧑‍🎓",
  },
  {
    key: "courses",
    label: "Khóa học",
    href: "/courses",
    group: "Học viên & Lịch",
    keywords: ["course", "khoa", "lop", "dao tao"],
    icon: "📚",
  },
  {
    key: "schedule",
    label: "Lịch học",
    href: "/schedule",
    group: "Học viên & Lịch",
    keywords: ["lich", "ca hoc", "calendar", "lich hoc"],
    icon: "🗓️",
  },
  {
    key: "admin-student-content",
    label: "Nội dung học viên",
    href: "/admin/student-content",
    group: "Học viên & Lịch",
    keywords: ["noi dung", "tai lieu", "hoc lieu"],
    icon: "📝",
  },
  {
    key: "instructors",
    label: "Giáo viên thực hành",
    href: "/admin/instructors",
    group: "Học viên & Lịch",
    keywords: ["giao vien", "instructor", "thuc hanh", "gv"],
    icon: "👨‍🏫",
  },
  {
    key: "automation-run",
    label: "Tự động hóa",
    href: "/automation/run",
    group: "Tự động hoá",
    keywords: ["automation", "chay tay", "workflow", "tu dong"],
    icon: "🔄",
  },
  {
    key: "automation-logs",
    label: "Nhật ký tự động hóa",
    href: "/automation/logs",
    group: "Tự động hoá",
    keywords: ["log", "lich su chay", "retry", "job"],
    icon: "📜",
  },
  {
    key: "admin-cron",
    label: "Vận hành tự động",
    href: "/admin/cron",
    group: "Tự động hoá",
    keywords: ["cron", "scheduler", "lich chay"],
    icon: "⏱️",
  },
  {
    key: "admin-scheduler",
    label: "Lập lịch",
    href: "/admin/scheduler",
    group: "Tự động hoá",
    keywords: ["scheduler", "lich", "job"],
    icon: "📆",
  },
  {
    key: "admin-worker",
    label: "Tiến trình gửi tin",
    href: "/admin/worker",
    group: "Tự động hoá",
    keywords: ["worker", "queue", "hang doi", "tin nhan"],
    icon: "📨",
  },
  {
    key: "admin-n8n",
    label: "Luồng n8n",
    href: "/admin/n8n",
    group: "Tự động hoá",
    keywords: ["n8n", "workflow", "integration", "ops"],
    icon: "🔗",
  },
  {
    key: "admin-automation-monitor",
    label: "Giám sát luồng tự động",
    href: "/admin/automation-monitor",
    group: "Tự động hoá",
    keywords: ["giam sat", "luong tu dong", "monitor", "run", "job", "log"],
    icon: "📡",
  },
  {
    key: "admin-ops",
    label: "Báo cáo",
    href: "/admin/ops",
    group: "Tự động hoá",
    keywords: ["ops pulse", "marketing", "bao cao", "report"],
    icon: "📊",
  },
  {
    key: "marketing",
    label: "Báo cáo marketing",
    href: "/marketing",
    group: "Tự động hoá",
    keywords: ["marketing", "meta", "ads", "bao cao"],
    icon: "📣",
  },
  {
    key: "admin-users",
    label: "Người dùng",
    href: "/admin/users",
    group: "Quản trị",
    keywords: ["user", "tai khoan", "phan quyen"],
    icon: "👥",
  },
  {
    key: "admin-permissions",
    label: "Phân quyền",
    href: "/admin/phan-quyen",
    group: "Quản trị",
    keywords: ["rbac", "phan quyen", "group", "override"],
    icon: "🔐",
  },
  {
    key: "admin-guide",
    label: "Hướng dẫn vận hành",
    href: "/admin/guide",
    group: "Quản trị",
    keywords: ["huong dan", "runbook", "quy trinh", "tai lieu"],
    icon: "📖",
  },
  {
    key: "admin-ai-guide",
    label: "Hướng dẫn Trợ lý công việc",
    href: "/admin/huong-dan-ai",
    group: "Quản trị",
    keywords: ["tro ly cong viec", "huong dan ai", "goi y", "kpi"],
    icon: "🤖",
  },
  {
    key: "admin-ops-guide",
    label: "Sổ tay vận hành",
    href: "/admin/huong-dan-van-hanh",
    group: "Quản trị",
    keywords: ["so tay", "huong dan van hanh", "quy trinh", "van hanh"],
    icon: "📒",
  },
  {
    key: "api-hub",
    label: "API Hub",
    href: "/api-hub",
    group: "Quản trị",
    keywords: ["api", "integration", "tich hop", "hub", "swagger"],
    icon: "🌐",
  },
  {
    key: "admin-branches",
    label: "Chi nhánh",
    href: "/admin/branches",
    group: "Quản trị",
    keywords: ["branch", "co so", "dia diem"],
    icon: "🏢",
  },
  {
    key: "admin-assign-leads",
    label: "Phân khách hàng",
    href: "/admin/assign-leads",
    group: "Quản trị",
    keywords: ["phan bo", "chia lead", "chia khach"],
    icon: "🔀",
  },
  {
    key: "admin-notifications",
    label: "Quản trị thông báo",
    href: "/admin/notifications",
    group: "Quản trị",
    keywords: ["thong bao", "notification"],
    icon: "🔔",
  },
  {
    key: "admin-tuition-plans",
    label: "Gói học phí",
    href: "/admin/tuition-plans",
    group: "Quản trị",
    keywords: ["hoc phi", "tuition", "goi hoc phi"],
    icon: "💳",
  },
  {
    key: "hr-attendance",
    label: "Chấm công",
    href: "/hr/attendance",
    group: "Quản trị",
    keywords: ["attendance", "cong", "diem danh nhan su"],
    icon: "✅",
  },
  {
    key: "hr-salary-profiles",
    label: "Hồ sơ lương",
    href: "/hr/salary-profiles",
    group: "Quản trị",
    keywords: ["salary profile", "muc luong", "ho so"],
    icon: "📄",
  },
];
